### ISSUE TITLE
cobra command crashes on Mac OS X

### ISSUE THREAD

**Issue by timesking** [spf13/cobra#202]
go 1.5.1
mac os x

cobra command crashed! just go get and run

```
➜  cobra ✗ go get -v github.com/spf13/cobra/cobra
github.com/spf13/cobra (download)
github.com/BurntSushi/toml
github.com/spf13/cobra
github.com/mitchellh/mapstructure
github.com/spf13/viper
github.com/spf13/cobra/cobra/cmd
github.com/spf13/cobra/cobra


➜  cobra ✗ cobra
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x82787]

goroutine 1 [running]:
text/template.errRecover(0xc8200bbc60)
	/usr/local/Cellar/go/1.5.1/libexec/src/text/template/exec.go:100 +0xbb
strings.indexFunc(0x0, 0x38c0a0, 0x3bb6b0, 0x25cb00, 0x25cba0)
	/usr/local/Cellar/go/1.5.1/libexec/src/strings/strings.go:594 +0x47
strings.TrimLeftFunc(0x0, 0x38c0a0, 0x3bb6b0, 0x0, 0x0)
	/usr/local/Cellar/go/1.5.1/libexec/src/strings/strings.go:549 +0x4a
strings.TrimFunc(0x0, 0x38c0a0, 0x3bb6b0, 0x0, 0x0)
	/usr/local/Cellar/go/1.5.1/libexec/src/strings/strings.go:572 +0x41
strings.TrimSpace(0x0, 0x38c0a0, 0x0, 0x0)
	/usr/local/Cellar/go/1.5.1/libexec/src/strings/strings.go:654 +0x43
reflect.Value.call(0x28b380, 0x3bb520, 0x13, 0x32d468, 0x4, 0xc82009c640, 0x1, 0x1, 0x0, 0x0, ...)
	/usr/local/Cellar/go/1.5.1/libexec/src/reflect/value.go:432 +0x120a
reflect.Value.Call(0x28b380, 0x3bb520, 0x13, 0xc82009c640, 0x1, 0x1, 0x0, 0x0, 0x0)
	/usr/local/Cellar/go/1.5.1/libexec/src/reflect/value.go:300 +0xb1
text/template.(*state).evalCall(0xc8200bbbf0, 0x25cba0, 0xc820075260, 0x58, 0x28b380, 0x3bb520, 0x13, 0x744900, 0xc820079200, 0x3bd0ff, ...)
	/usr/local/Cellar/go/1.5.1/libexec/src/text/template/exec.go:602 +0xb38
text/template.(*state).evalFunction(0xc8200bbbf0, 0x25cba0, 0xc820075260, 0x58, 0xc820079230, 0x744900, 0xc820079200, 0xc820075140, 0x1, 0x1, ...)
	/usr/local/Cellar/go/1.5.1/libexec/src/text/template/exec.go:475 +0x33d
text/template.(*state).evalCommand(0xc8200bbbf0, 0x25cba0, 0xc820075260, 0x58, 0xc820079200, 0x25cba0, 0xc820075260, 0x58, 0x0, 0x0, ...)
	/usr/local/Cellar/go/1.5.1/libexec/src/text/template/exec.go:372 +0x1e9
text/template.(*state).evalPipeline(0xc8200bbbf0, 0x25cba0, 0xc820075260, 0x58, 0xc8200868c0, 0x25cba0, 0xc820075260, 0x58)
	/usr/local/Cellar/go/1.5.1/libexec/src/text/template/exec.go:345 +0x180
text/template.(*state).walk(0xc8200bbbf0, 0x25cba0, 0xc820075260, 0x58, 0x744708, 0xc820079260)
	/usr/local/Cellar/go/1.5.1/libexec/src/text/template/exec.go:180 +0x135
text/template.(*state).walk(0xc8200bbbf0, 0x25cba0, 0xc820075260, 0x58, 0x744870, 0xc8200791a0)
	/usr/local/Cellar/go/1.5.1/libexec/src/text/template/exec.go:188 +0x776
text/template.(*state).walkIfOrWith(0xc8200bbbf0, 0x13, 0x329ec0, 0x4d2ca0, 0x16, 0xc820086870, 0xc8200791a0, 0x0)
	/usr/local/Cellar/go/1.5.1/libexec/src/text/template/exec.go:216 +0x2a1
text/template.(*state).walk(0xc8200bbbf0, 0x329ec0, 0x4d2ca0, 0x16, 0x7447e0, 0xc820070580)
	/usr/local/Cellar/go/1.5.1/libexec/src/text/template/exec.go:199 +0x627
text/template.(*state).walk(0xc8200bbbf0, 0x329ec0, 0x4d2ca0, 0x16, 0x744870, 0xc8200790b0)
	/usr/local/Cellar/go/1.5.1/libexec/src/text/template/exec.go:188 +0x776
text/template.(*Template).Execute(0xc820070480, 0x744420, 0xc820084008, 0x329ec0, 0x4d2ca0, 0x0, 0x0)
	/usr/local/Cellar/go/1.5.1/libexec/src/text/template/exec.go:143 +0x2b6
github.com/spf13/cobra.tmpl(0x744420, 0xc820084008, 0x3bd0e0, 0x68, 0x329ec0, 0x4d2ca0, 0x0, 0x0)
	/Users/timesking/Projects/golang/goget14/src/github.com/spf13/cobra/cobra.go:133 +0x29b
github.com/spf13/cobra.(*Command).Help(0x4d2ca0, 0x0, 0x0)
	/Users/timesking/Projects/golang/goget14/src/github.com/spf13/cobra/command.go:765 +0xbd
github.com/spf13/cobra.(*Command).HelpFunc.func1(0x4d2ca0, 0xc820074180, 0x0, 0x0)
	/Users/timesking/Projects/golang/goget14/src/github.com/spf13/cobra/command.go:213 +0x29
github.com/spf13/cobra.(*Command).Execute(0x4d2ca0, 0x740000, 0xc820074630)
	/Users/timesking/Projects/golang/goget14/src/github.com/spf13/cobra/command.go:616 +0x516
github.com/spf13/cobra/cobra/cmd.Execute()
	/Users/timesking/Projects/PlanX/ServerX/src/github.com/spf13/cobra/cobra/cmd/root.go:38 +0x27
main.main()
	/Users/timesking/Projects/PlanX/ServerX/src/github.com/spf13/cobra/cobra/main.go:19 +0x14

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
	/usr/local/Cellar/go/1.5.1/libexec/src/runtime/asm_amd64.s:1696 +0x1
```

**Comment by anthonyfok** [comment]
Hi @timesking, thanks for reporting this, though I could not reproduce it on Linux.  Perhaps other Cobra users/developers running Mac OS X can confirm.

But just to eliminate external factors like outdated dependencies, could you please run the following and see if you can reproduce the crash?

    go get -u -v github.com/spf13/cobra
    go get -u -v github.com/spf13/cobra/cobra
    cobra

Many thanks!
Anthony

**Comment by timesking** [comment]
Nothing changed with your commands.

**Comment by apriendeau** [comment]
@anthonyfok I will take a look because I have a mac to replicate.

**Comment by apriendeau** [comment]
I wasn't able to recreate. @timesking it could be an old package that it is depending on. Did you try removing the old `github.com/spf13/cobra` directory? Then rerun you command because it worked with a clean build.

**Comment by spf13** [comment]
@timesking are you still experiencing this? I haven't been able to reproduce it on a mac (or windows or linux). Please add as much information as you can if it's still an issue. If it's not, then please close this.

**Comment by timesking** [comment]
go get -v -u github.com/spf13/cobra/cobra

I got another problem while installing
```
github.com/spf13/cobra (download)
github.com/spf13/pflag (download)
github.com/spf13/viper (download)
github.com/BurntSushi/toml (download)
github.com/hashicorp/hcl (download)
github.com/kr/pretty (download)
github.com/kr/text (download)
github.com/magiconair/properties (download)
github.com/mitchellh/mapstructure (download)
github.com/spf13/cast (download)
github.com/spf13/jwalterweatherman (download)
Fetching https://gopkg.in/fsnotify.v1?go-get=1
Parsing meta tags from https://gopkg.in/fsnotify.v1?go-get=1 (status code 200)
get "gopkg.in/fsnotify.v1": found meta tag main.metaImport{Prefix:"gopkg.in/fsnotify.v1", VCS:"git", RepoRoot:"https://gopkg.in/fsnotify.v1"} at https://gopkg.in/fsnotify.v1?go-get=1
gopkg.in/fsnotify.v1 (download)
Fetching https://gopkg.in/yaml.v2?go-get=1
Parsing meta tags from https://gopkg.in/yaml.v2?go-get=1 (status code 200)
get "gopkg.in/yaml.v2": found meta tag main.metaImport{Prefix:"gopkg.in/yaml.v2", VCS:"git", RepoRoot:"https://gopkg.in/yaml.v2"} at https://gopkg.in/yaml.v2?go-get=1
gopkg.in/yaml.v2 (download)
github.com/hashicorp/hcl/hcl/strconv
github.com/spf13/pflag
github.com/kr/text
github.com/magiconair/properties
github.com/hashicorp/hcl/hcl/token
github.com/kr/pretty
github.com/hashicorp/hcl/hcl/ast
github.com/hashicorp/hcl/hcl/scanner
github.com/hashicorp/hcl/hcl/parser
github.com/hashicorp/hcl/json/token
github.com/hashicorp/hcl/json/scanner
github.com/mitchellh/mapstructure
github.com/hashicorp/hcl/json/parser
github.com/spf13/jwalterweatherman
github.com/spf13/cast
github.com/hashicorp/hcl
gopkg.in/fsnotify.v1
gopkg.in/yaml.v2
github.com/spf13/cobra
github.com/spf13/viper
github.com/spf13/cobra/cobra/cmd
github.com/spf13/cobra/cobra
# github.com/spf13/cobra/cobra
/Users/timesking/Projects/golang/goget14/pkg/darwin_amd64/github.com/spf13/cobra.a(_go_.o): object is [darwin amd64 go1.5.1 X:none] expected [darwin amd64 go1.5.2 ]
/Users/timesking/Projects/golang/goget14/pkg/darwin_amd64/github.com/BurntSushi/toml.a(_go_.o): object is [darwin amd64 go1.5.1 X:none] expected [darwin amd64 go1.5.2 ]
/Users/timesking/Projects/golang/goget14/pkg/darwin_amd64/gopkg.in/yaml.v2.a(_go_.o): object is [darwin amd64 go1.5.1 X:none] expected [darwin amd64 go1.5.2 ]
/Users/timesking/Projects/golang/goget14/pkg/darwin_amd64/github.com/mitchellh/mapstructure.a(_go_.o): object is [darwin amd64 go1.5.1 X:none] expected [darwin amd64 go1.5.2 ]
github.com/spf13/cobra/cobra/cmd.init.1: call to external function github.com/spf13/cobra.(*Command).AddCommand
github.com/spf13/cobra/cobra/cmd.init.2: call to external function github.com/spf13/cobra.(*Command).Flags
github.com/spf13/cobra/cobra/cmd.init.6: call to external function github.com/spf13/cobra.OnInitialize
github.com/spf13/viper.(*Viper).UnmarshalKey: call to external function github.com/mitchellh/mapstructure.Decode
github.com/spf13/viper.(*Viper).Unmarshal: call to external function github.com/mitchellh/mapstructure.WeakDecode
github.com/spf13/viper.init: call to external function github.com/BurntSushi/toml.init
panic: runtime error: slice bounds out of range

goroutine 1 [running]:
cmd/link/internal/ld.decodetype_ptrdata(0xc820d412c0, 0x5)
	/usr/local/Cellar/go/1.5.2/libexec/src/cmd/link/internal/ld/decodesym.go:75 +0x8b
cmd/link/internal/ld.(*GCProg).AddSym(0xc8228812b0, 0xc820ceadc0)
	/usr/local/Cellar/go/1.5.2/libexec/src/cmd/link/internal/ld/data.go:1097 +0x1ec
cmd/link/internal/ld.dodata()
	/usr/local/Cellar/go/1.5.2/libexec/src/cmd/link/internal/ld/data.go:1345 +0x1268
cmd/link/internal/ld.Ldmain()
	/usr/local/Cellar/go/1.5.2/libexec/src/cmd/link/internal/ld/pobj.go:242 +0x1ebb
cmd/link/internal/amd64.Main()
	/usr/local/Cellar/go/1.5.2/libexec/src/cmd/link/internal/amd64/obj.go:44 +0x19
main.main()
	/usr/local/Cellar/go/1.5.2/libexec/src/cmd/link/main.go:26 +0x189
```

**Comment by spf13** [comment]
You appear to have stale .o files. Please run `go clean` 

This sometimes happens when you have multiple versions of go sharing a $gopath

**Comment by timesking** [comment]
Thanks, it is multiple gopath problem. 
It can not be reproduced right now.
