### ISSUE TITLE
panic: "XX" shorthand is more than one ASCII character

### ISSUE THREAD

**Issue by decentral1se** [spf13/cobra#2208]
```go
FooNewCommand.Flags().StringVarP(
	&gitName,
	"git-name",
	"gn",
	"",
	"Git (user) name to do commits with",
)
```

`gn` is not accepted?

This is triggered when I run the following:

```go
doc.GenManTree(cmd, header, "/tmp")
```

from [here](https://github.com/spf13/cobra/blob/main/site/content/docgen/man.md). So, for manpage generation.

```bash
./foo manpage
panic: "gn" shorthand is more than one ASCII character

goroutine 1 [running]:
github.com/spf13/pflag.(*FlagSet).AddFlag(0xc000127600, 0xc0000c8d20)
	/home/d/hack/cc/a/vendor/github.com/spf13/pflag/flag.go:864 +0x485
github.com/spf13/pflag.(*FlagSet).VarPF(0xc000127600, {0x12d8518, 0x1b63ef0}, {0x1190200, 0x8}, {0x11821ee, 0x2}, {0x11bfd42, 0x22})
	/home/d/hack/cc/a/vendor/github.com/spf13/pflag/flag.go:831 +0x105
github.com/spf13/pflag.(*FlagSet).VarP(0x0?, {0x12d8518?, 0x1b63ef0?}, {0x1190200?, 0xc000537db8?}, {0x11821ee?, 0x11a835b?}, {0x11bfd42?, 0xc000582690?})
	/home/d/hack/cc/a/vendor/github.com/spf13/pflag/flag.go:837 +0x32
github.com/spf13/pflag.(*FlagSet).StringVarP(0xc000127600, 0x7?, {0x1190200, 0x8}, {0x11821ee, 0x2}, {0x0?, 0x10?}, {0x11bfd42, 0x22})
	/home/d/hack/cc/a/vendor/github.com/spf13/pflag/string.go:42 +0x88
coopcloud.tech/a/cli/foo.init.2()
	/home/d/hack/cc/a/cli/r/new.go:106 +0x5d
```

**Comment by marckhouzam** [comment]
Short flags can only be one character
